# Generated by Django 3.1 on 2023-04-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('volume', 'volume'), ('ball_size', 'ball_size'), ('capacity', 'capacity')], max_length=100),
        ),
    ]
